export type Place = {slug:string;name:string;tagline:string;code:string;color:string;asset:string;questions:{title:string;options:string[]}[]};
export const careerIdeas:Record<string,string[]> = {
 A:['Graphic Designer','Film Editor','Content Producer','Animator','Creative Director'],
 I:['Data Analyst','Research Scientist','UX Researcher','Lab Technician','Software Engineer'],
 E:['Entrepreneur','Account Manager','Marketing Manager','Project Lead','Sales Strategist'],
 S:['Teacher','Counsellor','Nurse','Community Worker','People Partner'],
 R:['Product Designer','Engineer','Technician','Architect','Industrial Designer'],
 C:['Accountant','Operations Coordinator','Business Analyst','Records Officer','Financial Planner']
};
export const places:Place[] = [
 {slug:'theatre',name:'Theatre & Film Club',tagline:'Performing, creating, expressing',code:'A',color:'#ffcb05',asset:'Theatre & Film Club.png',questions:[{title:'I am...',options:['creative','imaginative','innovative','sensitive','expressive','original']},{title:'I can...',options:['sketch, draw, paint','sing, act or dance','write stories','design visuals','play music','make videos']},{title:'I like to...',options:['perform for others','create new ideas','visit galleries','tell stories','make music','explore fashion']}]},
 {slug:'science',name:'Science & Research Lab',tagline:'Analysing, discovering, solving',code:'I',color:'#ed1b2f',asset:'Science & Research Lab.png',questions:[{title:'I am...',options:['curious','logical','observant','precise','independent','thoughtful']},{title:'I can...',options:['solve problems','analyse data','run experiments','research topics','spot patterns','explain results']},{title:'I like to...',options:['discover how things work','study nature','test ideas','read science news','use technology','solve puzzles']}]},
 {slug:'business',name:'The Business District',tagline:'Leading, persuading, achieving',code:'E',color:'#09045b',asset:'The Business District.png',questions:[{title:'I am...',options:['confident','ambitious','energetic','persuasive','decisive','sociable']},{title:'I can...',options:['lead a team','sell an idea','make decisions','plan a project','negotiate','speak in public']},{title:'I like to...',options:['start projects','meet new people','organise events','take risks','compete','influence others']}]},
 {slug:'community',name:'Community & Wellness Centre',tagline:'Helping, teaching, connecting',code:'S',color:'#ef63dd',asset:'Community & Wellness Centre.png',questions:[{title:'I am...',options:['caring','patient','friendly','understanding','cooperative','supportive']},{title:'I can...',options:['listen well','teach others','support a team','resolve conflict','give advice','care for people']},{title:'I like to...',options:['help others','work in groups','volunteer','teach skills','improve wellbeing','build community']}]},
 {slug:'maker',name:'Maker Workshop',tagline:'Building, fixing, making',code:'R',color:'#43ceda',asset:'Maker Workshop.png',questions:[{title:'I am...',options:['practical','active','reliable','hands-on','persistent','down-to-earth']},{title:'I can...',options:['build things','repair equipment','use tools','work outdoors','follow plans','operate machines']},{title:'I like to...',options:['make real objects','fix problems','work with materials','be physically active','see tangible results','learn by doing']}]},
 {slug:'records',name:'Bank & Records Office',tagline:'Organising, checking, recording',code:'C',color:'#185bd7',asset:'Bank & Records Office.png',questions:[{title:'I am...',options:['organised','careful','accurate','responsible','systematic','efficient']},{title:'I can...',options:['manage records','work with numbers','follow procedures','check details','plan schedules','use spreadsheets']},{title:'I like to...',options:['keep things orderly','complete clear tasks','organise information','work with data','make lists','create routines']}]}];
